name: ⏰ Будильник для Render

on:
  schedule:
    # Запускать робота каждые 12 минут
    - cron: '*/12 * * * *'
  # Кнопка, чтобы можно было запустить вручную для проверки
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Будим сервер Render
        run: |
          curl -X POST https://ml-agent-ijht.onrender.com \
          -H "Content-Type: application/json" \
          -d '{"query":"ping"}'
